Repository krissen/polleninformation, pull requests merged in 2025-07, with the labels that each got.

#4 remove all occurences of show_polls to ensure - every available poll-information is shown not only constants
  custom_components/polleninformation/api.py
  custom_components/polleninformation/const.py
  custom_components/polleninformation/sensor.py
Labels: bug

#11 (sensor) Fix location slug, round two
  custom_components/polleninformation/utils.py
Labels: bug

#15 Remove unused constant
  custom_components/polleninformation/sensor.py
Labels: codex

#14 Remove outdated air quality references
  README.md
  info.md
Labels: codex

#16 Fix options editing and share API key
  custom_components/polleninformation/__init__.py
  custom_components/polleninformation/config_flow.py
  custom_components/polleninformation/options_flow.py
Labels: bug, codex

#18 Add sensor scale documentation
  README.md
  info.md
Labels: documentation, codex

#19 Update README with description of allergen level scale
  README.md
  info.md
Labels: documentation

#21 Changed user-facing string 'United Kingdom' to 'Great Britain'
  custom_components/polleninformation/config_flow.py
  custom_components/polleninformation/const.py
  custom_components/polleninformation/utils.py
Labels: bug, config
